import type { WorkoutRoutine } from "../features/workout/model/workoutTypes";

export const presetWorkoutRoutines: WorkoutRoutine[] = [
  {
    id: "push-routine",
    name: "푸시 루틴",
    description: "가슴, 어깨 전면, 삼두 중심의 상체 밀기 루틴",
    category: "push",
    difficulty: "intermediate",
    estimatedMinutes: 60,
    exercises: [
      {
        id: "bench-press",
        name: "Bench Press",
        sets: 4,
        reps: "5~8",
        restSeconds: 150,
        memo: "견갑 고정, 허리 과신전 주의, 바 경로 일정하게 유지.",
      },
      {
        id: "incline-db-press",
        name: "Incline Dumbbell Press",
        sets: 3,
        reps: "8~12",
        restSeconds: 120,
        memo: "팔꿈치를 너무 벌리지 말고 윗가슴 수축에 집중.",
      },
      {
        id: "shoulder-press",
        name: "Shoulder Press",
        sets: 3,
        reps: "8~10",
        restSeconds: 120,
        memo: "허리 젖히지 말고 코어 고정.",
      },
      {
        id: "lateral-raise",
        name: "Lateral Raise",
        sets: 4,
        reps: "12~20",
        restSeconds: 60,
        memo: "승모근 개입 줄이고 팔꿈치로 들어올리는 느낌.",
      },
      {
        id: "cable-triceps-pushdown",
        name: "Cable Triceps Pushdown",
        sets: 3,
        reps: "10~15",
        restSeconds: 60,
        memo: "팔꿈치 고정, 끝지점에서 삼두 수축.",
      },
    ],
  },
  {
    id: "pull-routine",
    name: "풀 루틴",
    description: "등, 후면 어깨, 이두 중심의 상체 당기기 루틴",
    category: "pull",
    difficulty: "intermediate",
    estimatedMinutes: 60,
    exercises: [
      {
        id: "pull-up",
        name: "Pull Up",
        sets: 4,
        reps: "가능한 만큼",
        restSeconds: 150,
        memo: "반동 줄이고 가슴을 바 쪽으로 당기는 느낌.",
      },
      {
        id: "barbell-row",
        name: "Barbell Row",
        sets: 4,
        reps: "6~10",
        restSeconds: 150,
        memo: "허리 말림 주의, 등을 먼저 고정하고 당기기.",
      },
      {
        id: "lat-pulldown",
        name: "Lat Pulldown",
        sets: 3,
        reps: "8~12",
        restSeconds: 120,
        memo: "팔로 잡아당기지 말고 팔꿈치를 아래로 내린다는 느낌.",
      },
      {
        id: "seated-cable-row",
        name: "Seated Cable Row",
        sets: 3,
        reps: "10~12",
        restSeconds: 90,
        memo: "몸통 흔들지 말고 등 중앙 수축.",
      },
      {
        id: "face-pull",
        name: "Face Pull",
        sets: 3,
        reps: "12~20",
        restSeconds: 60,
        memo: "후면 어깨와 견갑 안정화에 집중.",
      },
      {
        id: "db-curl",
        name: "Dumbbell Curl",
        sets: 3,
        reps: "10~15",
        restSeconds: 60,
        memo: "팔꿈치 고정, 반동 금지. 인간이 늘 반동을 사랑하니까 특히 주의.",
      },
    ],
  },
  {
    id: "leg-routine",
    name: "하체 루틴",
    description: "스쿼트, 힙힌지, 단관절 보조운동을 포함한 하체 루틴",
    category: "leg",
    difficulty: "intermediate",
    estimatedMinutes: 65,
    exercises: [
      {
        id: "back-squat",
        name: "Back Squat",
        sets: 4,
        reps: "5~8",
        restSeconds: 180,
        memo: "무릎과 발끝 방향 일치, 복압 유지.",
      },
      {
        id: "romanian-deadlift",
        name: "Romanian Deadlift",
        sets: 4,
        reps: "8~10",
        restSeconds: 150,
        memo: "허리로 숙이지 말고 엉덩이를 뒤로 빼는 힙힌지.",
      },
      {
        id: "leg-press",
        name: "Leg Press",
        sets: 3,
        reps: "10~15",
        restSeconds: 120,
        memo: "무릎을 완전히 잠그지 말고 대퇴사두 수축 유지.",
      },
      {
        id: "walking-lunge",
        name: "Walking Lunge",
        sets: 3,
        reps: "각 다리 10~12",
        restSeconds: 90,
        memo: "상체 세우고 앞발 뒤꿈치로 밀어내기.",
      },
      {
        id: "leg-curl",
        name: "Leg Curl",
        sets: 3,
        reps: "10~15",
        restSeconds: 75,
        memo: "햄스트링 수축 지점에서 잠깐 멈추기.",
      },
      {
        id: "standing-calf-raise",
        name: "Standing Calf Raise",
        sets: 4,
        reps: "12~20",
        restSeconds: 60,
        memo: "최하단 스트레칭, 최상단 수축을 확실히.",
      },
    ],
  },
];
